name: to_do_list
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+3
  flutter_calendar_carousel: 2.4.2
  table_calendar: ^3.0.1
  shared_preferences: ^2.0.0
  stop_watch_timer: ^2.0.0
  numberpicker: ^2.1.2
  audioplayers: ^0.20.1
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^9.1.5
  cupertino_icons: ^1.0.6
  provider: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/notification.mp3
